version: '3.2'

services:
  buildpack-infra:
    image: sponsoroo-infra
    build: .
    environment:
      - ENV
      - BOTO_CONFIG=/infra/configs/.boto
    volumes:
      - ~/.config:/root/.config
      - ~/.kube:/root/.kube
